---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./crunchy-postgres-operator/ks.yaml
  - ./userinit-controller/ks.yaml
  - ./keycloak/ks.yaml
  # - ./forgejo/ks.yaml
  # - ./harbor/ks.yaml
  # - ./rabbitmq-operator/ks.yaml
  # - ./woodpecker/ks.yaml
