apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-infrastructure
  namespace: infrastructure
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      remoteNamespace: infrastructure
      auth:
        serviceAccount:
          name: external-secrets
          namespace: infrastructure
