---
commonLabels:
  app.kubernetes.io/instance: flux-instance
  ingress.samoth.eu/kube-apiserver: allow
  ingress.samoth.eu/prometheus: allow
  egress.samoth.eu/dns: allow
  egress.samoth.eu/kube-apiserver: allow
  egress.samoth.eu/internet-github: allow
instance:
  cluster:
    networkPolicy: false
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "https://github.com/Samoth69/Fern.git"
    ref: refs/heads/main
    path: kubernetes/flux/cluster
    interval: 15m
  kustomize:
    patches:
      # Increase the number of workers
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=10
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --requeue-dependency=5s
          - op: replace
            path: /spec/template/spec/containers/0/resources/limits
            value:
              memory: 2048Mi
        target:
          kind: Deployment
          name: "(kustomize-controller|helm-controller|source-controller)"
      # Enable in-memory kustomize builds
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --concurrent=20
          - op: replace
            path: /spec/template/spec/volumes/0
            value:
              name: temp
              emptyDir:
                medium: Memory
        target:
          kind: Deployment
          name: kustomize-controller
      # Enable Helm repositories caching
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --helm-cache-max-size=10
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --helm-cache-ttl=60m
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --helm-cache-purge-interval=5m
        target:
          kind: Deployment
          name: source-controller
      # Flux near OOM detection for Helm
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --feature-gates=OOMWatch=true
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --oom-watch-memory-threshold=95
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --oom-watch-interval=500ms
        target:
          kind: Deployment
          name: helm-controller
