---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kyverno
  namespace: flux-system
spec:
  targetNamespace: kyverno
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/kyverno/kyverno/app
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kyverno-policies
  namespace: flux-system
spec:
  targetNamespace: kyverno
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kyverno
  path: ./kubernetes/apps/kyverno/kyverno/policies
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  timeout: 5m
