---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cidr-group-cloudflare.yaml
  - ./cidr-group-lan.yaml
  - ./cidr-group-truenas.yaml
