---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: rook-ceph-cluster
  values:
    operatorNamespace: storage
    monitoring:
      enabled: true
      createPrometheusRules: true
      prometheusRuleOverrides:
        CephHealthWarning:
          for: "60m"
        CephMonDiskspaceLow:
          disabled: true
        CephNodeDiskspaceWarning:
          disabled: true
    toolbox:
      enabled: true
    ingress:
      dashboard:
        host:
          name: ceph.fern.samoth.eu
          path: "/"
          pathType: Prefix
        ingressClassName: traefik-internal
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v19.2.3
      dashboard:
        ssl: false
      logCollector:
        enabled: false
      cephConfig:
        global:
          bdev_enable_discard: "true" # quote
          bdev_async_discard_threads: "1" # quote
          osd_class_update_on_start: "false" # quote
          device_failure_prediction_mode: local # requires mgr module
          bluestore_slow_ops_warn_lifetime: "7200" # 2h
        mgr:
          mgr/crash/warn_recent_interval: "7200" # 2h
        mds:
          # https://github.com/rook/rook/issues/14220#issuecomment-2270086717
          mds_dir_max_commit_size: "80" # orig: 10
          # https://www.suse.com/fr-fr/support/kb/doc/?id=000019740
          mds_cache_trim_threshold: "288358" # orig: 262144
          mds_cache_trim_decay_rate: "0.900000" # orig: 1.000000
          mds_cache_memory_limit: "4724464025" # orig: 4294967296
          mds_recall_max_caps: "33000" # orig: 30000
          mds_recall_max_decay_rate: "1.350000" # orig: 1.500000
        mon:
          # https://docs.ceph.com/en/latest/rados/operations/health-checks/#mon-disk-low
          mon_data_avail_warn: "15" # orig: 30
      network:
        provider: host
        connections:
          requireMsgr2: true
      mgr:
        modules:
          - name: prometheus
            enabled: true
          - name: diskprediction_local
            enabled: true
          - name: insights
            enabled: true
          - name: pg_autoscaler
            enabled: true
          - name: rook
            enabled: true
      resources:
        mgr:
          requests:
            cpu: 50m
            memory: 768Mi
          limits:
            memory: 2Gi
        mon:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            memory: 1Gi
        osd:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            memory: 6Gi
        mgr-sidecar:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 256Mi
        crashcollector:
          requests:
            cpu: 1m
            memory: 10Mi
          limits:
            memory: 60Mi
        exporter:
          requests:
            cpu: 5m
            memory: 20Mi
          limits:
            memory: 128Mi
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "fern-akame"
            devices:
              # full nvme drive passthrough by proxmox
              - name: "sdb"
                deviceClass: nvme
          - name: "fern-felix"
            devices:
              - name: "nvme0n1"
          - name: "fern-nagumo"
            devices:
              - name: "nvme0n1"
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          parameters:
            imageFormat: "2"
            imageFeatures: layering,fast-diff,object-map,deep-flatten,exclusive-lock
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/fstype: ext4
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-blockpool
      isDefault: true
      deletionPolicy: Delete
    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
          metadataServer:
            activeCount: 1
            activeStandby: true
            placement:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                      - key: app
                        operator: In
                        values:
                        - rook-ceph-mds
                    topologyKey: "kubernetes.io/hostname"
            resources:
              limits:
                memory: "4Gi"
              requests:
                cpu: "30m"
                memory: "1Gi"
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          pool: data0
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: "Immediate"
          annotations: {}
          labels: {}
          mountOptions: []
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
            csi.storage.k8s.io/fstype: ext4
    cephFileSystemVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-filesystem
      isDefault: true
      deletionPolicy: Delete
    cephObjectStores:
      - name: "ceph-objectstore"
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            hostNetwork: false
            port: 80
            instances: 2
            placement:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                      - key: app
                        operator: In
                        values:
                        - rook-ceph-rgw
                    topologyKey: "kubernetes.io/hostname"
            healthCheck:
              bucket:
                interval: 60s
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 5m
                memory: 256Mi
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          parameters:
            region: us-east-1
        ingress:
          enabled: false
