---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 5m
  values:
    injector:
      enabled: false
    server:
      ingress:
        enabled: true
        hosts:
          - host: vault.fern.samoth.eu
            paths: []
      networkPolicy:
        enabled: true
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: infrastructure
                podSelector:
                  matchLabels:
                    app.kubernetes.io/instance: external-secrets
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: routing
                podSelector:
                  matchLabels:
                    app.kubernetes.io/instance: traefik-internal-routing
            ports:
              - protocol: TCP
                port: 8200
    ui:
      enabled: true
      serviceType: "ClusterIP"
      externalPort: 8200
