apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-s3-database-backup
type: Opaque
stringData:
    s3.conf: ENC[AES256_GCM,data:jZN7icxKdejv2yJk9Bx1OvxvzVfJfXHQAvEqQHzb/XHekq0Buag2YDzEopdM7mMz2vDwoQHzI8Ck0shxI8CpUoW8ISPTBYIhNZ+ilpBrrpO8k2+MhlPnvyGXwcgVUJW7XSBC8liNBAzxVwXB8oeZbUsxBJ1Vr808R8pY7A38C2v7Oc9uQ6g=,iv:9e/cH6UTJrRWnNy1bHOcCnn11ONFhDZuRAiIUMUXmIY=,tag:C8CyvqXcA1r7VnrZ43CeWA==,type:str]
sops:
    age:
        - recipient: age1dn7j4227qd9msjn6cueaxkut4tnshy4vmqs25gphdpf88ftqnvusll2cqm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV2ZaLyttLzJsNURuOUZB
            My9rMXl2UjZqenJnZ2lvbEhPNnl6RnE0V2hzCllNUFFGMVJXeG1tcFVKVlhVb08w
            NkpxWWFqdHNRa2FYK3VTU1RoZjYyYWMKLS0tIFpwTWpZem5kbTJZcHg1QUJWWjJm
            eG9XUUNsYnJJdkNqSGVrZnZsUEZick0KbWPFUtzpf9NCPgVl1A+fcLi3Thn5R9sS
            Qrofw5FRGaoAuEmRMXlqY5CTJYG7fiNrAPKHhY6IX/i7sNdlhYontQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T20:21:43Z"
    mac: ENC[AES256_GCM,data:2zhtmRkDmS5EffAcwuX+ej2Ib/Z5uv29HtqZMdXyr+6HvJfim62x5iTKLmP1skw4THgv7EMLyNCV8ftrD/8M5sobVf8N4527yt6vkDq5S94alKHdEaaUuUAg+wEOIASqBx6MkPM3Yi9I7HYsK2BBEZpv+Ysc5SNp7DXXtFh4iGo=,iv:EIlL+w9PCWopL2Rjet6SjIg5SC28m5GA0RbjymPvcNU=,tag:vvxSstn58q4HHZPJIffT1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
