apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-s3-database-backup
type: Opaque
stringData:
    s3.conf: ENC[AES256_GCM,data:QpLZpPtJcsnTkjDC3LgxGm+rSg0NwNbTwDxKQlxS2EDWdkTkNViBFYb8yO5sZWc+Yb1PaexPabo90N56j+FRotfoxxGv/cMw33jTUgOrQsGwFY94eVzzTf59tEPMSq4BY6oin979hYpjeKHRAVvpSmRuAj0hh/Sod+5bf6YwB0cngMQekfb/RBt3ss89,iv:FbNhWWVAE0SJg3NwN45TVcEAvxxsiAWkE83BA67c6rc=,tag:TLskpmVjZV9Y+vV68tIKSw==,type:str]
sops:
    age:
        - recipient: age1dn7j4227qd9msjn6cueaxkut4tnshy4vmqs25gphdpf88ftqnvusll2cqm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV2ZaLyttLzJsNURuOUZB
            My9rMXl2UjZqenJnZ2lvbEhPNnl6RnE0V2hzCllNUFFGMVJXeG1tcFVKVlhVb08w
            NkpxWWFqdHNRa2FYK3VTU1RoZjYyYWMKLS0tIFpwTWpZem5kbTJZcHg1QUJWWjJm
            eG9XUUNsYnJJdkNqSGVrZnZsUEZick0KbWPFUtzpf9NCPgVl1A+fcLi3Thn5R9sS
            Qrofw5FRGaoAuEmRMXlqY5CTJYG7fiNrAPKHhY6IX/i7sNdlhYontQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T17:01:47Z"
    mac: ENC[AES256_GCM,data:XTNBajLEfg+t5SMohMzUxaPdDQCakV2lXuKV5nG4qpWJY2ejQX/8di/kQu42WM4kxtDRsMBf+/Zt0hzXX0Fq67cytoaHk9m1KU4IwJ/au0zXWXLWsHVxOlHOmKmLGuzVR6Y4g3cNVsziKzkCUL/dRRcMSXzZJPYM2oEgGXdv8a0=,iv:rmwMTJLBLAwAYz2Na1VJFJL5LtVDS301hjktboTwHC0=,tag:qIno0FbnWP7PjVtGtN8VJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
