---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crunchy-postgres-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pgo
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    singleNamespace: false
    debug: false
    disable_check_for_upgrades: true
    install:
      clusterLabels:
        app.kubernetes.io/name: pgo
    metadata:
      labels:
        egress.samoth.eu/dns: allow
        egress.samoth.eu/kube-apiserver: allow
