# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-guardian
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-guardian
  driftDetection:
    mode: enabled
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    replace: true
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    namespace:
      name: system-priv
    controller:
      image:
        repository: ghcr.io/xentra-ai/images/guardian-controller
        pullPolicy: IfNotPresent
        tag: v0.0.19
    broker:
      image:
        repository: ghcr.io/xentra-ai/images/guardian-broker
        pullPolicy: IfNotPresent
        tag: "v0.0.19"
    database:
      image:
        repository: postgres
        pullPolicy: IfNotPresent
        tag: "17.5"
      persistence:
        enabled: true
        existingClaim: "kube-guardian"
