# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: ingress-network-policy
spec:
  endpointSelector:
    matchExpressions:
      - key: reserved:ingress
        operator: Exists
      - key: gateway-name:external
        operator: Exists
  ingress:
    - fromCIDRSet:
      # - cidrGroupRef: group-lan
      - cidrGroupRef: group-cloudflare
