# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: elastic
      interval: 5m
  values:
    refs:
      enforceRBAC: true
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 100Mi
