# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname woodpecker
  namespace: flux-system
spec:
  targetNamespace: infrastructure
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/infrastructure/woodpecker/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: crunchy-postgres-operator
    - name: rook-ceph-cluster
    - name: external-secrets
  components:
    - ../../../../components/postgresql/
  postBuild:
    substitute:
      APP: *appname
      POSTGRES_DATA_SIZE: 1Gi
  patches:
    - patch: |
        - op: remove
          path: /spec/dataSource
      target:
        kind: PostgresCluster
