---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 30m
  releaseName: rook-ceph
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  values:
    crds:
      enabled: true
    csi:
      cephFSKernelMountOptions: ms_mode=prefer-crc
      enableLiveness: true
      serviceMonitor:
        enabled: true
      csiRBDProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-resizer
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-attacher
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-snapshotter
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 64Mi
            limits:
              memory: 1Gi
        - name : csi-omap-generator
          resource:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi

      csiRBDPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi

      csiCephFSProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-resizer
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-attacher
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-snapshotter
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi

      csiCephFSPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 10Mi
              cpu: 10m
            limits:
              memory: 256Mi
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 256Mi
    enableDiscoveryDaemon: true
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources:
      requests:
        memory: 64Mi
        cpu: 100m
      limits:
        memory: 1Gi
    discover:
      resources: |
        '{"resources":{"requests":{"memory":"80Mi","cpu":"1m"},"limits":{"memory":"512Mi"}}}'
