# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: host-firewall
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: ""
  ingress:
  - fromEntities:
    - cluster
  - fromCIDR:
      - ${TRUSTED_CIDR_01}
    toPorts:
    - ports:
      # kubernetes-api-ingress
      - port: "6443"
        protocol: TCP
      # apid-ingress
      - port: "50000"
        protocol: TCP
      # trustd-ingress
      - port: "50001"
        protocol: TCP
  - fromCIDR:
      - ${TRUSTED_CIDR_01}
    icmps:
      - fields:
          - family: IPv4
            type: EchoRequest
