apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
spec:
  defaultCertificate:
    secretName: fern-prod-tls-secret
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: default
spec:
  minVersion: VersionTLS13
