apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden
type: Opaque
stringData:
  admin-token: ENC[AES256_GCM,data:4I+O9PhfSbMdAh+VhltWoIdP3prELnlfhlpwL1g3BRs=,iv:2Mlrvy2Slp0TzGVefFTIFwW0J8gELLonKdLhrlIveF4=,tag:N3ILseLE3yJBA2BDgN8K0Q==,type:str]
sops:
  age:
    - recipient: age1dn7j4227qd9msjn6cueaxkut4tnshy4vmqs25gphdpf88ftqnvusll2cqm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTXc4ZnBPcVY2SzdZT29B
        UXg5RW5KTnFTdG5nK3VrNm1VTGw4WjQ3QUE4CjRzVmpnVHJZZ1BNRUxYbGNHdVow
        dUh0WTUvaDFQaVpNRlpFWlZZbkY4NEkKLS0tIFdtYXYvMk1ia0ZiMWh1L3h1VXU5
        UWlNMVRPZ1kyTEN0RnlIaW4wOUJHTUkKXwgI1jd3OJyi2A2BlaBoENmpIXAsnXIe
        IdgW/xJM45nn5vLmsyhyvhtdugh5JDvjEdogU4FgQlC46iXjdDiatA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-28T16:39:48Z"
  mac: ENC[AES256_GCM,data:rrwdrCWf0UQMCKtAjjoJpg8/rB3YCa7/ohs6oJa8SiAOd6wotU0Im3t0LtBocN4fqajaoPNv4imvql5/pmzQOqWiphaD3+6XxQmFtlt5Ohstivrf8zjFLYkKthXVx2U0gMa09g2sbvqmeX8S7axh4bh759WeSXYTRJdNfhlmTXw=,iv:efHPwpXJML4sgeUXqe8LWyenCPLPpkhtBDkMrIv+Fsc=,tag:yW9YHCXy5fK2w3Sq7DVOSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
