---
grafanaDashboard:
  enabled: true
service:
  registry:
    hostPort: 29999
serviceMonitor:
  enabled: true
spegel:
  containerdSock: /run/containerd/containerd.sock
  containerdRegistryConfigPath: /etc/cri/conf.d/hosts
  resolveLatestTag: false
  additionalMirrorRegistries:
    - https://harbor.fern.samoth.eu
# Graceful Helmfile to HelmRelease takeover
commonLabels:
  helm.toolkit.fluxcd.io/name: spegel
  helm.toolkit.fluxcd.io/namespace: kube-system
