# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname buildkitd
  namespace: flux-system
spec:
  targetNamespace: infrastructure-priv
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/infrastructure-priv/buildkitd/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
