# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/upgrade.cattle.io/plan_v1.json
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos
spec:
  version: ${TALOS_VERSION}
  concurrency: 1
  exclusive: true
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: Exists
  secrets:
    - name: system-upgrade-controller
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  serviceAccountName: system-upgrade-controller
  # this does in fact exist : https://github.com/rancher/system-upgrade-controller/blob/master/doc/plan.md#planspec
  window:
    days:
      - su
      - mo
      - tu
      - we
      - th
      - fr
      - sa
    startTime: "05:00"
    endTime: "07:00"
    timeZone: Europe/Paris
  upgrade:
    image: ghcr.io/jfroy/tnu:0.4.4
    args:
      - --node=$(SYSTEM_UPGRADE_NODE_NAME)
      - --tag=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
