apiVersion: v1
kind: Secret
metadata:
    name: curseforge-api
    namespace: games
stringData:
    CF_API_KEY: ENC[AES256_GCM,data:gNO558qcWQhqUiQ2KOHY1Mu8XR0QqxLG38ATNNZ4e8v1qEW39ZJ71gzPdWM5hv/UsoTsya4EBM3XUrGo,iv:UHlI999xmhl/GyRwPHVQyyLcWEaNwS8W3AxNhgDS/Jk=,tag:rqCWWX6T2bpHe5aMh0TQZQ==,type:str]
sops:
    age:
        - recipient: age1dn7j4227qd9msjn6cueaxkut4tnshy4vmqs25gphdpf88ftqnvusll2cqm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZll3T1RtTkxQYUhEYXJN
            QXlFTnU5OEk1bnk5Njd5U0Qyc2prY0FTbFFVCjNXa25KeWVaRElKcUhXaUFHbHhZ
            SzBlTmlTVlVIYnBaUE14MEVnKzJVVzAKLS0tIG5lY3dZU3lCUlRsRDRSL0VMMjB3
            VFExYkV1Q09weEdmKzNzNVBQcWVFR2sKRQIncpRLZTW65068tbKEcRjRa1/AmhV0
            NmN3uTsnEk2FBQNW6IVyfQMhKb/EmLiFgcaFRQUhopwXEHBUp+iiTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-04T21:08:27Z"
    mac: ENC[AES256_GCM,data:YayLAfXcNkXIwuBSs3dol+EM6ZPYp7cZBLwGSHd4XREV0a20outrcBrpPYL/3Fpz42CD52iUeIH/1eQKesvcnsSLYssPOV9cUD/uutM260keklVbtORMC+wsJ/96fuWgkZ9IJJtny0HKJN1hiRj2qE4/tlqP3u1SjJ6eLzlS0tY=,iv:0h04TQaDfcO6nVTMSUvXSQQezBXZ6dBomo3SzoQEM6g=,tag:2C93j1MumMHgmdQz0UfCDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
