# see https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors
apiVersion: v1
kind: Service
metadata:
  name: garage-proxy
  annotations:
    traefik.ingress.kubernetes.io/service.nativelb: "true"
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3900
      targetPort: 3900
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: garage-proxy-slice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: garage-proxy
addressType: IPv4
ports:
  - name: http # should match with the name of the service port defined above
    appProtocol: http
    protocol: TCP
    port: 3900
endpoints:
  - addresses:
    - '192.168.0.22'
    conditions:
      ready: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.io/ingressroute_v1alpha1.json
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: garage-proxy-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`garage-proxy.fern.samoth.eu`)
      services:
        - name: garage-proxy
          port: 3900
