# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fern-cert
spec:
  secretName: fern-prod-tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
  commonName: "fern.samoth.eu"
  dnsNames:
    - "fern.samoth.eu"
    - "*.fern.samoth.eu"
  renewBefore: 720h #30d
