---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: rabbitmq-cluster-operator
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    global:
      defaultStorageClass: ceph-block
    watchAllNamespaces: false
    watchNamespaces:
      - apps
    resources:
      requests:
        cpu: 2m
        memory: 16Mi
      limits:
        memory: 256Mi
    networkPolicy:
      kubeAPIServerPorts:
        - 6443
    msgTopologyOperator:
      enabled: false
