---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 30m
  values:
    fullnameOverride: victoria-logs
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    server:
      enabled: true
      replicaCount: 1
      retentionPeriod: 14d
      retentionDiskSpaceUsage: 20GB
      persistentVolume:
        size: 21Gi
      ingress:
        enabled: true
        ingressClassName: traefik-internal
        hosts:
          - name: victoria-logs.fern.samoth.eu
            path:
              - /
            port: http
      serviceMonitor:
        enabled: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Observability
      labels:
        grafana_dashboard: "1"
