apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:WjogK8sH4UOnd/Bc+ba3ZHHXn6O2elDjFvxg9pVoMJs=,iv:/xgI4W0k5MRSigEe/zOeJ8u1DO8nJ29mbBC1M091qTs=,tag:8V2a5JYFyNR8Js+814xiwQ==,type:str]
sops:
  age:
    - recipient: age1dn7j4227qd9msjn6cueaxkut4tnshy4vmqs25gphdpf88ftqnvusll2cqm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZzFqbWtMcVRUemVZcTJK
        SVBMaVk0ZWRkVE9GRTlUb1BKZ0ZIQUpRcndjClpadkFQM2xPamF3LzFPbDlXMGlw
        NTZaY1JnUnlkRHVtd0ZQZkZKTk9Oa0EKLS0tICtaQ2wrWGFzNlNkTTM2VUtPRWFk
        ajdpUlJQaFVCVmZLS2VSTjkweFF4Q00KZOmaITCq7acQ0l7f9cS517QRL8JnH5q4
        Fd5pH3VcXLpHXR7THKVMxJAxDaxTF2P4VYvfjLXLphTwCoPvwsg3Mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-29T13:47:51Z"
  mac: ENC[AES256_GCM,data:QSfF6zxWVhjLgKTxw9FpdVHW92pTkvv2qeT9M4wxEep/LH2q4hHCr+56PYxvM0nMWu1g64M0e72vTKJHFS0V4ot4h6TSpEbWvMksdLUsT1UNufDPccp/PYpe5yDQwNn/w/EhY8LWXMYGXvXQ5XHQbv5QP4PPeDdb3tqwKMdzVqg=,iv:BC3mI+F3jXPRbasbWhp/D2JqSG2cVMHQY+oNsk02fUU=,tag:fDa/JWNgYn7wegdrbPGQ4w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
