# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.18.1
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
      interval: 5m
  values:
    master:
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 5m
          memory: 16Mi
    worker:
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 5m
          memory: 16Mi
    prometheus:
      enable: true
